name: Release mosdns

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          check-latest: true

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
          check-latest: true

      - name: Install UPX
        run: sudo apt-get update && sudo apt-get install -y upx

      - name: Build
        run: python ./release.py
        env:
          CGO_ENABLED: '0'

      - name: Prepare original binaries
        run: |
          mkdir -p release/original
          cp ./release/mosdns* release/original/

      - name: Upload original binaries
        uses: actions/upload-artifact@v4
        with:
          name: mosdns-original
          path: ./release/original/*

      - name: UPX compress binaries
        run: |
          find ./release/mosdns* -type f -exec upx --best --lzma {} \;

      - name: Prepare UPX binaries
        run: |
          mkdir -p release/upx
          cp ./release/mosdns* release/upx/

      - name: Upload UPX binaries
        uses: actions/upload-artifact@v4
        with:
          name: mosdns-upx
          path: ./release/upx/*
